--ClubCreation
INSERT INTO dbo.Club ( Name ) VALUES ('Frederikssund');
INSERT INTO dbo.Club ( Name ) VALUES ('Hillerød');

--TeamCreation
INSERT INTO dbo.Team ( Name, Club ) VALUES ('Panda', '1');
INSERT INTO dbo.Team ( Name, Club ) VALUES ('Abe', '1');
INSERT INTO dbo.Team ( Name, Club ) VALUES ('Tiger', '1');
INSERT INTO dbo.Team ( Name, Club ) VALUES ('Drage', '1');
INSERT INTO dbo.Team ( Name, Club ) VALUES ('Voksen', '2');


--PANDAHOLD
INSERT INTO dbo.Student ( Name, Team) VALUES ('Natasha E. S. Jensen','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Storm B. Askbo','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Victoria A. Rygh Jessen','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Kadir A.K. Ziyanak','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Astrid Boldt','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Neva V. Torrendrup','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Zinelle Fjord','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Naja S. Dahl','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Victor V. Torrendrup','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Ole Winkler_kofoed','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Stefanie Bergholt','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Nathalia Friberg-Richelsen','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Alexander Sejrbo','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Isac Munk-Stendevad','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Theo Munk-Stendevad','1');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Alfred G. Jensen','1');

--ABEHOLD
INSERT INTO dbo.Student ( Name, Team) VALUES ('Emil B. Nielsen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Line Gøttsche','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Kevin Pagh','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Jonathan Kristensen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Gavin E. S. Jensen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Emily Grelck','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Axel Grelck','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Ronja E. S. Nielsen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Villads H. Hedberg','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Jeppe L. Frederiksen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Liv Asmus Bro','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Andreas Joachim Petersen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Gustav V. S. Juhl','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Nicklas Petersen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Alexander Boldt','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Marcus Liu Hansen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Wendy He Forss','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Jibrail Lahchich','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Albert L. Sonnenborg','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Carol Dragos','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Maya Sirbu','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Ida B.M Madsen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Andrea K. Andersen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Tobias. C.A. Danielsen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Odin Taiming-Wang Rasmussen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Frans A. P. Henriksen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Oliver Barfod','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Julius Pedersen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Jonathan Krarup','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Anders Lindegård Jensen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Max Bo Møller','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Hjalte Høgsted','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Caroline E. Struve','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Victoria Bergholt','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Rasmus Vilsbøll','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Annamarie Vilsbøll','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Valdemar Kjeldergaard','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('William Kolind Rees','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Elias Baillie','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Alberte L. Frederiksen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Frederik Arne Wowereit','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Kristian Arne Wowereit','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Magnus G. Jensen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Jessica Klitgaard','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Tobias Rømer-Jensen','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Gustav Linde','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Emilio Rosas-Norman','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Leandro Rosas-Norman','2');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Nikolaj Ørvad','2');


--TIGERHOLD
INSERT INTO dbo.Student ( Name, Team) VALUES ('Benjamin Villadsen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Helena H. Hedberg','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Daniel Jensen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Enya J. Berlick','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Marcus Tran','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Kasper S. Winther','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Mads B. Nielsen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Malthe H. Hedberg','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Aina X. Berlick','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Sif Ena Sloth Nielsen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Ida Kaa R. Pedersen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Silas A. Villumsen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Ea H. Lauesen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Jonas Fuhr Høyer','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Jonas P Møller','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Benjamin Kristensen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Gustav Gøttsche','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Andreas Hansen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Simon Pagh','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Erwin Nerwa','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Sahil Yasin','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Laura Abildstrup','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Matilde S. G. Lindhard','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Louise Kunkel','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Josefine Kunkel','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Arthur Chen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Elias Alexandrakis','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('George Alexandrakis','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Annika Orloff','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Rikke Thestrup','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Victor H. Olsen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Kasper Kjeldgaard','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Simon A. Danielsen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Linnea S. E. Steffensen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Marika Ø. Svensson','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Sara Lak','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Sam Osani','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Viktoria N. Jakobsen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Majse Vick-Nielsen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Daniel Alex Andersen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Erik Pagh Goodwin','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Ronja Høgsted','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Sebastian Bloch','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Anders T. Hansen','3');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Aise','3');


--DRAGEHOLD
INSERT INTO dbo.Student ( Name, Team) VALUES ('Søren Kluge','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Michelle Sirak','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Janus Søndergaard Hjorth','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Benjamin Latroch','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Jesper Falkenberg','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Michala Hammer Reichenbach','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Mike Lund Johansen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Lars Boucheny','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Jakob Khoi Pedersen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Hannah La Cour','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Andreas Palner','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Michael Christensen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Benjamin B. Madsen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Martin Bech','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Frederik Loft','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Thomas Tran','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Mads S. Winther','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Jan Nikolaj Jessen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Neilsean Laulund Victorino','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Sebastian Michaelsen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Lonnie Hedberg','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Michael Steinmejer','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Martin B. Rasmussen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Max Møller','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Karin Kirsten Kaa Pedersen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Tom Bantz','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Kasper Sydney Jensen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Pernille Thorslev','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Benjamin Wang','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Christian R. Andersen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Michael Capion','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Subhanullah Otmanzi','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Mark Waltenburg','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Mikkel T. Pedersen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Hayat Kreinøe','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Sine Kreinøe','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Kim Boldt','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Anders B. Bisgaard','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Caroline Oppenlænder','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Jan E. S. Jensen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Lasse H. Knudsen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Troels Jeppesen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Charlotte H. K. Poulsen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Harry Singh','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Rune H. Bak','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Cathrine D. B. Pedersen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Vigdis GunnarsDöttir','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Dag Tilma Hansen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Philip Hjorth','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Stefan Rasmussen','4');
INSERT INTO dbo.Student ( Name, Team) VALUES ('Anita Pagh','4');
